version: '3'
services:
  php74:
    build: ../../php
    # 指定镜像
    image: php-7.4-fpm
    restart: always
    # 通常php的端口不需要暴露
    # ports:
    #   - "9090:9000"
    networks:
      - appnet
    volumes:
      - ../../dockerfile/php/7.4/php.ini:/usr/local/etc/php/php.ini
      - ../../dockerfile/php/7.4/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ../../work/php:/var/www/
  nginx:
    image: openresty/openresty:alpine
    restart: always
    ports:
      - "8080:80"
      - "8081:81"
    networks:
      - appnet
    volumes:
      - ../../nginx/conf.d:/etc/nginx/conf.d
      - ../../nginx/logs:/usr/local/openresty/nginx/logs
      - ../../work/html:/var/www/html
networks:
  appnet: